### ISSUE TITLE
Start drafting content suggested by DS & Middleware team 

### ISSUE THREAD

**Issue by KateCourt** [NewcastleRSE/tools_and_practices#3]
Our aim for our next meeting is to create/update pages in the wiki for each topic. There's not need to aim straight for something perfect - make a start on a working document of notes and we'll all pitch in to develop it over time. 

If you would like to assign yourself to one of the sections, add yourself to the action list below. As we have 1:1s over the next few weeks, we'll talk more in detail about this.

Once you've made a start on the contents of the page you can check  it off here:

- [ ] Data Science best practice  - Kathryn
- [ ] Visualisation tools - Mike
- [ ] Databases - Jim
- [ ] Deployment: Azure, Docker, Terraform - Kate, Robin and Tiago
- [ ] HPC: Bede and Rocket, and how to be a good user
- [ ] Researcher tools: Matlab, R, R Shiny, Excel (best practice for researcher), Open refine, humanities section (TEI, xslt)
- [ ] Wireframing and UI/UX tools: Figma, Miro, Adobe XD
- [ ] Specialist languages: those outside of our core repertoire
- [ ] Wiki navigation

**Comment by tiagosousagarcia** [comment]
since it's still very fresh on my mind, I'm happy to take a stab at a specific deployment case (ML models for inference)

**Comment by kathryn-garside** [comment]
Unless anyone else wants to do it I can put together some stuff on HPC rocket & bede

**Comment by KateCourt** [comment]
Superseded by #5 and #6
