### ISSUE TITLE
Code snippets/examples in the repo?

### ISSUE THREAD

**Issue by tiagosousagarcia** [NewcastleRSE/tools_and_practices#4]
Might it be a good idea to use the (currently empty) repo to host examples of code we used for particular methods/services?

Having a link to a full implementation in the form of other projects is great but I can see cases where trolling through all the project files in search of a small snippet of code might be hard work. Also, there might be cases where we tried a particular avenue that ended up not working, that might be useful for someone else and harder to find in feature branches of the original project -- for example, I have quite a bit of exploratory code to deploy ML models in different services with different options that will not be used in the final project.

**Comment by KateCourt** [comment]
Great idea Tiago. I was similarly chatting to Robin W about where we could put some sample docker and terraform files - whether to put them in the cloud infrastructure repo or here - I think after reading your message they maybe belong here
